// ====================================
// QUIZ SUBMIT - PRODUCTION VERSION
// ====================================
// Webhook pro Business Health Quiz
// URL: /.netlify/functions/quiz-submit
// UPDATED: Using same pattern as fapi-webhook.js

// Supabase client helper
async function createSupabaseClient() {
  const { createClient } = await import('@supabase/supabase-js');
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_ANON_KEY // ✅ SAME AS PAYMENT WEBHOOK
  );
}

// Resend email sending function
async function sendEmail(to, subject, html) {
  console.log('📨 Sending email via Resend to:', to);
  
  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.RESEND_API_KEY}`, // ✅ SAME AS PAYMENT WEBHOOK
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'Podnikatelská Čtvrtka <kurz@podnikatelskactvrtka.cz>',
      to: [to],
      subject: subject,
      html: html,
    }),
  });
  
  console.log('📧 Resend Response Status:', response.status);
  
  if (!response.ok) {
    const error = await response.text();
    console.error('❌ Resend error:', error);
    throw new Error(`Email failed: ${error}`);
  }
  
  const data = await response.json();
  console.log(' Email sent via Resend:', data.id);
  return data;
}

// Main handler
export async function handler(event, context) {
  console.log('🚀 quiz-submit function called');
  
  // Only accept POST requests
  if (event.httpMethod !== 'POST') {
    console.log('❌ Wrong method:', event.httpMethod);
    return {
      statusCode: 405,
      body: JSON.stringify({ error: 'Method not allowed' })
    };
  }
  
  // Enable CORS
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Content-Type': 'application/json'
  };
  
  // Handle OPTIONS preflight request
  if (event.httpMethod === 'OPTIONS') {
    console.log('✅ OPTIONS preflight');
    return {
      statusCode: 200,
      headers,
      body: ''
    };
  }
  
  try {
    console.log('📦 Raw event body:', event.body);
    const { email, name, quizType, answers, result } = JSON.parse(event.body);
    
    console.log('📝 Quiz submission:', { email, quizType, category: result.category, score: result.score });
    console.log('📊 Full result object:', result);
    
    // Validate
    if (!email || !result) {
      console.error('❌ Missing required fields');
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({ error: 'Missing required fields' })
      };
    }
    
    // ──────────────────────────────────────────
    // 💾 SAVE TO SUPABASE
    // ──────────────────────────────────────────
    console.log('💾 Saving quiz results to Supabase...');
    const supabase = await createSupabaseClient();
    
    const { data: quizResult, error: insertError } = await supabase
      .from('quiz_results')
      .insert({
        email: email,
        name: name || email.split('@')[0],
        quiz_type: quizType,
        score: result.score,
        category: result.category,
        category_label: result.categoryLabel,
        risks: result.risks || [],
        recommendations: result.recommendations || [],
        answers: answers
        // ✅ created_at is auto-generated by database
      })
      .select()
      .single();
    
    if (insertError) {
      console.error('❌ Supabase insert error:', insertError);
      throw new Error(`Database error: ${insertError.message}`);
    }
    
    console.log('✅ Quiz results saved to Supabase:', quizResult.id);
    
    // ──────────────────────────────────────────
    // 🏷️ ADD TO SMARTEMAILING LIST 4
    // ─────────────────────────────────────────
    console.log('📤 Adding to Smartemailing list 4 (kvíz)...');
    
    try {
      const seApiKey = process.env.SMARTEMAILING_API_KEY;
      const seUsername = process.env.SMARTEMAILING_USERNAME;
      const seListId = process.env.SMARTEMAILING_LIST_KVIZ || '4'; // ✅ LIST 4 FOR QUIZ
      
      console.log('🔑 SmartEmailing credentials:', {
        hasUsername: !!seUsername,
        hasApiKey: !!seApiKey,
        listId: seListId
      });
      
      if (!seApiKey || !seUsername) {
        console.warn('⚠️ Missing SmartEmailing credentials - skipping');
      } else {
        const seAuthString = Buffer.from(`${seUsername}:${seApiKey}`).toString('base64');
        
        // ✅ USE SAME PATTERN AS PAYMENT WEBHOOK
        const seResponse = await fetch('https://app.smartemailing.cz/api/v3/import', {
          method: 'POST',
          headers: {
            'Authorization': `Basic ${seAuthString}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            settings: {
              update: true, // Update existing contacts
              field_policy: 'FILL_IN_EMPTY'
            },
            data: [{
              emailaddress: email,
              name: name || '',
              surname: '',
              contactlists: [{
                id: parseInt(seListId), // ✅ LIST 4
                status: 'confirmed'
              }]
              // ❌ REMOVED: customfields - need to configure correct IDs first
              // TODO: Add custom fields after checking SmartEmailing dashboard for correct IDs
            }]
          })
        });
        
        const seData = await seResponse.json();
        console.log('📥 SmartEmailing response:', seData);
        
        const successStatuses = ['ok', 'created'];
        if (seResponse.ok && successStatuses.includes(seData.status)) {
          console.log('✅ Added to Smartemailing:', seData.status);
        } else {
          console.error('⚠️ SmartEmailing failed:', seData);
        }
      }
    } catch (seError) {
      console.error('⚠️ SmartEmailing error (non-critical):', seError.message);
      // Don't fail the whole function if SE fails
    }
    
    // ──────────────────────────────────────────
    // 📧 SEND EMAIL WITH RESULTS
    // ──────────────────────────────────────────
    console.log('📨 Sending quiz results email...');
    
    const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin: 0; padding: 0; background-color: #f3f4f6; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background-color: #f3f4f6;">
    <tr>
      <td align="center" style="padding: 40px 20px;">
        <table role="presentation" width="600" cellspacing="0" cellpadding="0" border="0" style="max-width: 600px; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
          
          <!-- Header -->
          <tr>
            <td style="background: linear-gradient(135deg, #dc2626 0%, #15803d 100%); padding: 40px 20px; text-align: center;">
              <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 700;">
                🎁 Tvoje výsledky jsou tady!
              </h1>
            </td>
          </tr>
          
          <!-- Content -->
          <tr>
            <td style="padding: 40px 30px;">
              <p style="margin: 0 0 20px 0; color: #111827; font-size: 18px; line-height: 1.6;">
                Ahoj <strong>${name || 'podnikateli'}</strong>! 👋
              </p>
              
              <p style="margin: 0 0 20px 0; color: #374151; font-size: 16px; line-height: 1.6;">
                Tvůj byznys má skóre <strong style="color: #dc2626; font-size: 24px;">${result.score}%</strong>
              </p>
              
              <div style="background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%); border-radius: 12px; padding: 20px; margin: 20px 0; border-left: 4px solid #f59e0b;">
                <p style="margin: 0 0 10px 0; font-weight: 700; color: #92400e; font-size: 18px;">
                  📊 Tvoje kategorie: ${result.categoryLabel}
                </p>
                <p style="margin: 0; font-size: 14px; color: #78350f; line-height: 1.5;">
                  ${result.categoryDescription}
                </p>
              </div>
              
              ${result.risks && result.risks.length > 0 ? `
              <div style="margin: 30px 0;">
                <h2 style="color: #dc2626; font-size: 20px; margin: 0 0 15px 0;">⚠️ Na co si dát pozor:</h2>
                <ul style="margin: 0; padding-left: 20px; color: #374151;">
                  ${result.risks.map(risk => `<li style="margin-bottom: 8px;">${risk}</li>`).join('')}
                </ul>
              </div>
              ` : ''}
              
              ${result.recommendations && result.recommendations.length > 0 ? `
              <div style="margin: 30px 0;">
                <h2 style="color: #15803d; font-size: 20px; margin: 0 0 15px 0;">✅ Co dělat PRVNÍ:</h2>
                <ul style="margin: 0; padding-left: 20px; color: #374151;">
                  ${result.recommendations.map(rec => `<li style="margin-bottom: 8px;">${rec}</li>`).join('')}
                </ul>
              </div>
              ` : ''}
              
              <!-- CTA Button -->
              <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin: 30px 0;">
                <tr>
                  <td align="center">
                    <a href="https://podnikatelskactvrtka.cz/kviz/vysledky?email=${encodeURIComponent(email)}&score=${result.score}&category=${encodeURIComponent(result.category)}&name=${encodeURIComponent(name || email.split('@')[0])}&subScores=${encodeURIComponent(JSON.stringify(result.subScores || []))}" style="display: inline-block; background: linear-gradient(135deg, #dc2626 0%, #15803d 100%); color: #ffffff; text-decoration: none; padding: 16px 40px; border-radius: 8px; font-size: 18px; font-weight: 600; box-shadow: 0 4px 6px rgba(220, 38, 38, 0.3);">
                      🎄 Zobrazit kompletní výsledky a akční plán
                    </a>
                  </td>
                </tr>
              </table>
              
              <p style="margin: 20px 0 0 0; color: #6b7280; font-size: 14px; line-height: 1.6;">
                Přejeme ti úspěšný rok 2026! 🚀<br>
                <strong>Podnikatelská Čtvrtka</strong>
              </p>
            </td>
          </tr>
          
          <!-- Footer -->
          <tr>
            <td style="background-color: #f9fafb; padding: 30px; text-align: center; border-top: 1px solid #e5e7eb;">
              <p style="margin: 0; color: #6b7280; font-size: 14px;">
                Podnikatelská Čtvrtka<br>
                <a href="https://podnikatelskactvrtka.cz" style="color: #dc2626; text-decoration: none;">podnikatelskactvrtka.cz</a>
              </p>
            </td>
          </tr>
          
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
    `;
    
    try {
      // ✅ UNIFIED EMAIL SUBJECT with emoji + category
      const emoji = result.category === 'beginner' ? '🌱' :
                    result.category === 'critical' ? '🔴' :
                    result.category === 'unstable' ? '🟡' :
                    result.category === 'solid' ? '🟢' :
                    result.category === 'advanced' ? '💎' : '🎯';
      
      const categoryName = result.category === 'beginner' ? 'Začínáš' :
                           result.category === 'critical' ? 'Kritický stav' :
                           result.category === 'unstable' ? 'Nestabilní' :
                           result.category === 'solid' ? 'Solidní základ' :
                           result.category === 'advanced' ? 'Pokročilý' : 'Výsledky';
      
      await sendEmail(
        email,
        `${emoji} ${categoryName} (${result.score}%) - Tvůj model podnikání`,
        emailHtml
      );
      console.log('✅ Email sent successfully!');
    } catch (emailError) {
      console.error('❌ Email send failed:', emailError);
      // Don't throw - quiz was saved, email is bonus
    }
    
    // ──────────────────────────────────────────
    // ✅ SUCCESS
    // ──────────────────────────────────────────
    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({
        success: true,
        message: 'Quiz results saved and email sent',
        quizId: quizResult.id,
        score: result.score,
        category: result.category
      })
    };
    
  } catch (error) {
    console.error('❌ Quiz submission error:', error);
    
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({
        error: error.message || 'Failed to submit quiz'
      })
    };
  }
}