[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers pro security a performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache statických assetů
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify Functions optimalizace
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Lokální development ENV (pro netlify dev)
# ⚠️ NEPUSHUJ PRODUKČNÍ CREDENTIALS DO GITU!
# Pro produkci používej: Netlify Dashboard → Environment Variables
[context.dev.environment]
  SMARTEMAILING_USERNAME = "cipera@byznysuj.cz"
  SMARTEMAILING_API_KEY = "4gi28ahu9tmv2lop1y8dy36pmec4og2c8gwsjgxm"
  SMARTEMAILING_LIST_ID = "2"
